[profile.default]
src = "tests/helpers/contracts"
out = "tests/helpers/contracts/out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=sample-contracts/lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options